# This file was generated by GoReleaser. DO NOT EDIT.
cask "cast" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "cd3b159b99c60dde0b066bfd944cfefcef6b4b6a3cc4c014f785122cba58b9e9"
      url "https://github.com/ravistakumar/cast/releases/download/v#{version}/cast_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b9b0bc8cbb32ccfdb6e140a51614a00e528d2953d241e6039cf412ff21274730"
      url "https://github.com/ravistakumar/cast/releases/download/v#{version}/cast_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f7cd6b4db44b0b57b56f097543569f0601ed7c02a3064a168386c1b749fa5773"
      url "https://github.com/ravistakumar/cast/releases/download/v#{version}/cast_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "81fa99edc194d91d06a00f65055745f3380b224a828d852d3829ba65ab684845"
      url "https://github.com/ravistakumar/cast/releases/download/v#{version}/cast_linux_arm64.tar.gz"
    end
  end

  name "cast"
  desc "Compile one Agent Skill into harness-native skills for every coding agent"
  homepage "https://github.com/ravistakumar/cast"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cast"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cast"]
    end
  end

  # No zap stanza required

end
