# This file was generated by GoReleaser. DO NOT EDIT.
cask "cast" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "086e46b967760ecb3ad93e1569ec430e91515631815ae3fff29d17f0af50a9b4"
      url "https://github.com/ravistakumar/cast/releases/download/v#{version}/cast_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b9b1b8045ab5fad94a2167c60684c075145573e7dfe06828d70d2f97e3357d3d"
      url "https://github.com/ravistakumar/cast/releases/download/v#{version}/cast_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "87cf6db2fbb9db2e8bf603c3a76c07a77f735bab9d5ad36e01d4158e4b564046"
      url "https://github.com/ravistakumar/cast/releases/download/v#{version}/cast_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "061ae4b2ec4e9b35078c2a07fc94556fafc6bd9df8645d813cdb5b095284137d"
      url "https://github.com/ravistakumar/cast/releases/download/v#{version}/cast_linux_arm64.tar.gz"
    end
  end

  name "cast"
  desc "Compile one Agent Skill into harness-native skills for every coding agent"
  homepage "https://github.com/ravistakumar/cast"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cast"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cast"]
    end
  end

  # No zap stanza required

end
