# This file was generated by GoReleaser. DO NOT EDIT.
cask "cast" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "7b9c5540002a7933f88623dbf51d563da6251839eda268aef456ab94dbc9566e"
      url "https://github.com/ravistakumar/cast/releases/download/v#{version}/cast_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "63b51aef055cf1a9c881ba4b42254d88f260ae10ca6e09869bf01c4c15dda0e9"
      url "https://github.com/ravistakumar/cast/releases/download/v#{version}/cast_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b4f87993fc981017d2d9c935b229cbcaed0dbf108b37093bd86cb74102d58928"
      url "https://github.com/ravistakumar/cast/releases/download/v#{version}/cast_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "91a452b2ffe4e6e0241356d2c2b09dd59273cc7fffa5c2a5138084fcef6099f7"
      url "https://github.com/ravistakumar/cast/releases/download/v#{version}/cast_linux_arm64.tar.gz"
    end
  end

  name "cast"
  desc "Compile one Agent Skill into harness-native skills for every coding agent"
  homepage "https://github.com/ravistakumar/cast"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cast"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cast"]
    end
  end

  # No zap stanza required

end
