# This file was generated by GoReleaser. DO NOT EDIT.
cask "fan" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "842d123cd422fcf71cb9086c62a8bb2963581cf89f400a3e1be1c12376be86a0"
      url "https://github.com/ravistakumar/fan/releases/download/v#{version}/fan_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a830aa72b10872aca824ba86bf606296a6f5dc567ae5852897fa870d01a1dab8"
      url "https://github.com/ravistakumar/fan/releases/download/v#{version}/fan_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4b70431dbe0d9b459bf5bc3e7b09abe74d82dc9092515322a2a1bf5f9247c4f5"
      url "https://github.com/ravistakumar/fan/releases/download/v#{version}/fan_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4225aa3981c4a7ea0651d919d68877cd89ef56be3a1309cec933d3571e3b1aa0"
      url "https://github.com/ravistakumar/fan/releases/download/v#{version}/fan_linux_arm64.tar.gz"
    end
  end

  name "fan"
  desc "Agent-agnostic parallel coding-agent orchestrator"
  homepage "https://github.com/ravistakumar/fan"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fan"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fan"]
    end
  end

  # No zap stanza required

end
