# This file was generated by GoReleaser. DO NOT EDIT.
cask "fan" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "b7ea3325c4a528408a7e4e651e41b5642cc03bad3f1e704cf9d755e92db59d2c"
      url "https://github.com/ravistakumar/fan/releases/download/v#{version}/fan_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "16acb01944fde1d7a4b246afa1cc8eb268246bf84a4c197a30c81261aa16c4f2"
      url "https://github.com/ravistakumar/fan/releases/download/v#{version}/fan_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8965cd95153f27a18b0450556175d887b53127fa637d4181923ca501aaadf6a5"
      url "https://github.com/ravistakumar/fan/releases/download/v#{version}/fan_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c4d4d8bc8419b16b4a7a11317a5ec954b7eef2cd0be48e0ce0ccfefd4f11ce46"
      url "https://github.com/ravistakumar/fan/releases/download/v#{version}/fan_linux_arm64.tar.gz"
    end
  end

  name "fan"
  desc "Agent-agnostic parallel coding-agent orchestrator"
  homepage "https://github.com/ravistakumar/fan"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fan"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fan"]
    end
  end

  # No zap stanza required

end
