# This file was generated by GoReleaser. DO NOT EDIT.
cask "prr" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "95f75dabcdcdb62979ea54e89b02d7ed2e7e7729093ff2b51a913e9a81c4f2a7"
      url "https://github.com/ravistakumar/prr/releases/download/v#{version}/prr_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "613baa4e4696b5930a09bc5f59267810544ccc68a5ebb5a73c3a92761fed5265"
      url "https://github.com/ravistakumar/prr/releases/download/v#{version}/prr_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3f2bfc38a3be0df3030ead7befd8cb0a010c83f8780e0c1adabd0e30b8fdd3dd"
      url "https://github.com/ravistakumar/prr/releases/download/v#{version}/prr_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "77ef7fe031ebdfde3ba83d5c3876c275718ae460e33eb267808c7cbe44ef1951"
      url "https://github.com/ravistakumar/prr/releases/download/v#{version}/prr_linux_arm64.tar.gz"
    end
  end

  name "prr"
  desc "Refine your prompt before your AI coding agent runs it — a terminal prompt firewall for Claude Code and Codex"
  homepage "https://github.com/ravistakumar/prr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prr"]
    end
  end

  # No zap stanza required

end
