# This file was generated by GoReleaser. DO NOT EDIT.
cask "prr" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2094eea3cd439735b36121f82094c8734716c22209ec347c0bb7fbc8be5ff9da"
      url "https://github.com/ravistakumar/prr/releases/download/v0.1.0/prr_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3ab29292dfa01e00522c748d0d051cd63b2100ae827c1ba044fd3d72b135c1e3"
      url "https://github.com/ravistakumar/prr/releases/download/v0.1.0/prr_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b26af2f8d62891834c8944745cc8e03cf4eb7aae2695271b34d0302382b1f295"
      url "https://github.com/ravistakumar/prr/releases/download/v0.1.0/prr_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "68bd376e9ed3468dff5ef3554a8d21a4db6ea1809b8483e411dd2853fe7cf7bf"
      url "https://github.com/ravistakumar/prr/releases/download/v0.1.0/prr_linux_arm64.tar.gz"
    end
  end

  name "prr"
  desc "Refine your prompt before your AI coding agent runs it — a terminal prompt firewall for Claude Code and Codex"
  homepage "https://github.com/ravistakumar/prr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prr"]
    end
  end

  # No zap stanza required

end
