# This file was generated by GoReleaser. DO NOT EDIT.
cask "prr" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "3bd2506f8456bd54265082ee31e6f64ec41b32d9ad9bb3444d32be7242b08a82"
      url "https://github.com/ravistakumar/prr/releases/download/v#{version}/prr_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a7ee44860964008c90ea059a09c734f7b8e57591a365c38cbef7011c30532866"
      url "https://github.com/ravistakumar/prr/releases/download/v#{version}/prr_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0edff96e3c1d3169e7b4520f2de0d31719da6c7fb752d034eeaee6fb692df8d7"
      url "https://github.com/ravistakumar/prr/releases/download/v#{version}/prr_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "63b5b229e65cc877cc022ed25ab0b926ef660bcdd0571a71e4a76d41be654ed6"
      url "https://github.com/ravistakumar/prr/releases/download/v#{version}/prr_linux_arm64.tar.gz"
    end
  end

  name "prr"
  desc "Refine your prompt before your AI coding agent runs it — a terminal prompt firewall for Claude Code and Codex"
  homepage "https://github.com/ravistakumar/prr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prr"]
    end
  end

  # No zap stanza required

end
